version: "2.1"
services:
  plex:
    image: armm_plex:0.0.1
    container_name: plex
    networks:
      - back
      - red2
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - PLEX_CLAIM= #optional
    volumes:
      - /path/to/library:/config
      - /path/to/tvseries:/tv
      - /path/to/movies:/movies
    restart: unless-stopped
    ports: 
      - "8087:32400"
  plex2:
    image: armm_plex:0.0.1
    container_name: plex_2
    networks:
      - back
      - red2
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - PLEX_CLAIM= #optional
    volumes:
      - /path/to/library:/config
      - /path/to/tvseries:/tv
      - /path/to/movies:/movies
    restart: unless-stopped
    ports: 
      - "8088:32400"
  myvault:
      image: vault
      container_name: myvault
      networks: 
        - back 
      ports:
        - "8200:8200"
      volumes:
        - ./file:/vault/file:rw
        - ./config:/vault/config:rw
      cap_add:
        - IPC_LOCK
      entrypoint: vault server -config=/vault/config/vault.json
networks: 
  back:
  red2:
    driver: bridge