version: '3.3'
services:
  mysql:
    image: mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: pass
    volumes:
      - db:/var/lib/mysql
  apache:
    image: httpd
    ports:
      - '80:80'
    depends_on:
      - mysql
volumes:
  apache:
  db: